export const products = [
    {
        coverImage: './assets/img/phone-cover.jpg',
        name: 'Phone XL',
        price: 799,
        description: 'A large phone with one of the best screens',
        heading1: 'サンプルテキスト１',
        heading2: 'サンプルテキスト２',
        heading3: 'サンプルテキスト３',
        headingtext1: 'サンプルテキスト１サンプルテキスト１サンプルテキスト１サンプルテキスト１サンプルテキスト１',
        headingtext2: 'サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２',
        headingtext3: 'サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２',
    },
    {
        coverImage: './assets/img/phone-cover.jpg',
        name: 'Phone mini',
        price: 699,
        description: 'A great phone with one of the best cameras',
        heading1: 'サンプルテキスト１',
        heading2: 'サンプルテキスト２',
        heading3: 'サンプルテキスト３',
        headingtext1: 'サンプルテキスト１サンプルテキスト１サンプルテキスト１サンプルテキスト１サンプルテキスト１',
        headingtext2: 'サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２',
        headingtext3: 'サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２',
    },
    {
        coverImage: './assets/img/phone-cover.jpg',
        name: 'Phone Standard',
        price: 299,
        description: '',
        heading1: 'サンプルテキスト１',
        heading2: 'サンプルテキスト２',
        heading3: 'サンプルテキスト３',
        headingtext1: 'サンプルテキスト１サンプルテキスト１サンプルテキスト１サンプルテキスト１サンプルテキスト１',
        headingtext2: 'サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２',
        headingtext3: 'サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２',
    },
    {
        coverImage: './assets/img/phone-cover.jpg',
        name: 'Phone Special',
        price: 999,
        description: '',
        heading1: 'サンプルテキスト１',
        heading2: 'サンプルテキスト２',
        heading3: 'サンプルテキスト３',
        headingtext1: 'サンプルテキスト１サンプルテキスト１サンプルテキスト１サンプルテキスト１サンプルテキスト１',
        headingtext2: 'サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２',
        headingtext3: 'サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２サンプルテキスト２',
    }
]